"""empty message

Revision ID: 9008fef2c92e
Revises: 07d46e8c8791
Create Date: 2023-10-10 22:19:38.169822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9008fef2c92e'
down_revision = '07d46e8c8791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
